services:
  auth-db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - podcast-network

  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - podcast-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      CLUSTER_ID: ${KAFKA_CLUSTER_ID}

    ports:
      - "9092:9092"

    volumes:
      - kafka-data:/var/lib/kafka/data

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092"]
      interval: 10s
      timeout: 5s
      retries: 10

    restart: unless-stopped

    networks:
      - podcast-network

  kafka-init:
    image: confluentinc/cp-kafka:7.6.0

    depends_on:
      kafka:
        condition: service_healthy

    command: >
      bash -c '
      until kafka-topics
      --bootstrap-server kafka:9092
      --list; do
        echo "Waiting for Kafka...";
        sleep 5;
      done;

      kafka-topics
      --bootstrap-server kafka:9092
      --create
      --if-not-exists
      --topic podcast.user.register
      --partitions 1
      --replication-factor 1
      '

    restart: "no"

    networks:
      - podcast-network

volumes:
  auth-db-data:
  rabbitmq-data:
  kafka-data:

networks:
  podcast-network:
    driver: bridge
    name: podcast-network