name: Setup server

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check env file
        run: |
          if [ ! -f /home/deploy/.env ]; then
            echo "/home/deploy/.env not found"
            exit 1
          fi

      - name: Start infrastructure
        run: |
          docker compose \
            --env-file /home/deploy/.env \
            -f docker-compose.infra.yml \
            up -d

      - name: Show infrastructure status
        run: |
          docker compose \
            -f docker-compose.infra.yml \
            ps
      - name: Restart nginx
        run: docker restart podcast_service-nginx-1